# Generated by Django 4.0.4 on 2022-05-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_rubric_alter_bboard_options_alter_bboard_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bboard',
            old_name='rubic',
            new_name='rubric',
        ),
    ]
